// Code generated by shared/schema/gen.py from event.schema.json. DO NOT EDIT.

package event

type Actor struct {
	Pid  int64    `json:"pid"`
	Ppid int64    `json:"ppid"`
	Exe  string   `json:"exe"`
	Args []string `json:"args"`
	User string   `json:"user"`
}

type Target struct {
	Path   *string `json:"path,omitempty"`
	Socket *string `json:"socket,omitempty"`
}

type Metrics struct {
	CPUPct   *float64 `json:"cpu_pct,omitempty"`
	RSSBytes *int64   `json:"rss_bytes,omitempty"`
	TempC    *float64 `json:"temp_c,omitempty"`
}

type Event struct {
	ID         string   `json:"id"`
	Ts         int64    `json:"ts"`
	HostID     string   `json:"host_id"`
	Kind       string   `json:"kind"`
	Actor      Actor    `json:"actor"`
	Target     *Target  `json:"target,omitempty"`
	Metrics    *Metrics `json:"metrics,omitempty"`
	Source     string   `json:"source"`
	Confidence float64  `json:"confidence"`
}

// Event kinds (schema enum).
const (
	KindHeartbeat      = "heartbeat"
	KindProcessSpawn   = "process.spawn"
	KindProcessExit    = "process.exit"
	KindResourceSample = "resource.sample"
)

// Event sources (schema enum).
const (
	SourcePoll = "poll"
	SourceEbpf = "ebpf"
	SourceEs   = "es"
	SourceEtw  = "etw"
)

// ValidKinds is the closed set of schema kinds.
var ValidKinds = map[string]bool{"heartbeat": true, "process.spawn": true, "process.exit": true, "resource.sample": true}

// ValidSources is the closed set of schema sources.
var ValidSources = map[string]bool{"poll": true, "ebpf": true, "es": true, "etw": true}

// SchemaVersion is the schema's x-schema-version.
const SchemaVersion = 1
