#!/usr/bin/env python3
"""Codegen: shared/schema/event.schema.json -> Go struct + Python dataclass.

The JSON schema is the single source of truth (architecture.md §3.3). This emits:
  - daemon/internal/event/event_gen.go        (package event)
  - engine/causegraph/schema/event_gen.py     (dataclasses)

Deterministic output: `make gen && git diff --exit-code` is the drift gate (AC1).

Usage:
  python3 shared/schema/gen.py            # write both files
  python3 shared/schema/gen.py --check    # regen in-memory, diff vs committed, exit 1 on drift
  python3 shared/schema/gen.py --go-only --stdout   # print Go to stdout (used by tests)
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCHEMA = os.path.join(ROOT, "shared", "schema", "event.schema.json")
GO_OUT = os.path.join(ROOT, "daemon", "internal", "event", "event_gen.go")
PY_OUT = os.path.join(ROOT, "engine", "causegraph", "schema", "event_gen.py")

GEN_HEADER = "// Code generated by shared/schema/gen.py from event.schema.json. DO NOT EDIT."
PY_HEADER = "# Code generated by shared/schema/gen.py from event.schema.json. DO NOT EDIT."

# Go identifier overrides so acronyms read idiomatically and stay stable.
_GO_OVERRIDES = {
    "id": "ID", "ts": "Ts", "host_id": "HostID", "pid": "Pid", "ppid": "Ppid",
    "exe": "Exe", "args": "Args", "user": "User", "path": "Path", "socket": "Socket",
    "cpu_pct": "CPUPct", "rss_bytes": "RSSBytes", "temp_c": "TempC",
    "kind": "Kind", "source": "Source", "confidence": "Confidence",
    "actor": "Actor", "target": "Target", "metrics": "Metrics",
}


def go_name(key: str) -> str:
    if key in _GO_OVERRIDES:
        return _GO_OVERRIDES[key]
    return "".join(p.capitalize() for p in key.split("_"))


def load_schema() -> dict:
    with open(SCHEMA, encoding="utf-8") as f:
        return json.load(f)


# ---- Go ----

def _go_scalar(t: str) -> str:
    return {"integer": "int64", "number": "float64", "string": "string"}[t]


def _go_field(key: str, spec: dict, struct_types: dict) -> str:
    optional = spec.get("x-optional", False)
    tag = key + (",omitempty" if optional else "")
    t = spec["type"]
    if t == "object":
        gotype = "*" + struct_types[key] if optional else struct_types[key]
    elif t == "array":
        gotype = "[]" + _go_scalar(spec["items"]["type"])
    else:
        base = _go_scalar(t)
        gotype = "*" + base if optional else base
    return f'\t{go_name(key)} {gotype} `json:"{tag}"`'


def _go_struct(name: str, obj: dict, struct_types: dict) -> str:
    lines = [f"type {name} struct {{"]
    for key, spec in obj["properties"].items():
        lines.append(_go_field(key, spec, struct_types))
    lines.append("}")
    return "\n".join(lines)


def gen_go(schema: dict) -> str:
    props = schema["properties"]
    # nested object structs, named by their key
    struct_types = {k: go_name(k) for k, v in props.items() if v["type"] == "object"}
    out = [GEN_HEADER, "", "package event", ""]

    # nested structs first, in schema order
    for key, spec in props.items():
        if spec["type"] == "object":
            out.append(_go_struct(struct_types[key], spec, {}))
            out.append("")

    out.append(_go_struct("Event", schema, struct_types))
    out.append("")

    # enum constants
    kinds = props["kind"]["enum"]
    sources = props["source"]["enum"]
    out.append("// Event kinds (schema enum).")
    out.append("const (")
    for k in kinds:
        cname = "Kind" + "".join(p.capitalize() for p in k.replace(".", "_").split("_"))
        out.append(f'\t{cname} = "{k}"')
    out.append(")")
    out.append("")
    out.append("// Event sources (schema enum).")
    out.append("const (")
    for s in sources:
        out.append(f'\tSource{s.capitalize()} = "{s}"')
    out.append(")")
    out.append("")
    out.append("// ValidKinds is the closed set of schema kinds.")
    out.append("var ValidKinds = map[string]bool{" + ", ".join(f'"{k}": true' for k in kinds) + "}")
    out.append("")
    out.append("// ValidSources is the closed set of schema sources.")
    out.append("var ValidSources = map[string]bool{" + ", ".join(f'"{s}": true' for s in sources) + "}")
    out.append("")
    out.append(f"// SchemaVersion is the schema's x-schema-version.")
    out.append(f'const SchemaVersion = {schema["x-schema-version"]}')
    out.append("")
    return "\n".join(out)


# ---- Python ----

def _py_scalar(t: str) -> str:
    return {"integer": "int", "number": "float", "string": "str"}[t]


def _py_type(spec: dict, struct_types: dict, key: str) -> str:
    optional = spec.get("x-optional", False)
    t = spec["type"]
    if t == "object":
        base = struct_types[key]
    elif t == "array":
        base = "list[" + _py_scalar(spec["items"]["type"]) + "]"
    else:
        base = _py_scalar(t)
    return f"Optional[{base}]" if optional else base


def _py_dataclass(name: str, obj: dict, struct_types: dict) -> str:
    lines = ["@dataclass", f"class {name}:"]
    # required (no default) first, then optional, to satisfy dataclass ordering
    req, opt = [], []
    for key, spec in obj["properties"].items():
        pt = _py_type(spec, struct_types, key)
        if spec.get("x-optional", False):
            opt.append(f"    {key}: {pt} = None")
        else:
            req.append(f"    {key}: {pt}")
    lines += req + opt

    # from_dict
    lines.append("")
    lines.append("    @classmethod")
    lines.append("    def from_dict(cls, d: dict) -> \"%s\":" % name)
    lines.append("        return cls(")
    for key, spec in obj["properties"].items():
        t = spec["type"]
        optional = spec.get("x-optional", False)
        if t == "object":
            sub = struct_types[key]
            if optional:
                lines.append(f"            {key}=({sub}.from_dict(d['{key}']) if d.get('{key}') is not None else None),")
            else:
                lines.append(f"            {key}={sub}.from_dict(d['{key}']),")
        else:
            if optional:
                lines.append(f"            {key}=d.get('{key}'),")
            else:
                lines.append(f"            {key}=d['{key}'],")
    lines.append("        )")

    # to_dict (omits None optionals; nested objects recurse)
    lines.append("")
    lines.append("    def to_dict(self) -> dict:")
    lines.append("        d: dict = {}")
    for key, spec in obj["properties"].items():
        t = spec["type"]
        optional = spec.get("x-optional", False)
        acc = f"self.{key}"
        if t == "object":
            if optional:
                lines.append(f"        if {acc} is not None:")
                lines.append(f"            d['{key}'] = {acc}.to_dict()")
            else:
                lines.append(f"        d['{key}'] = {acc}.to_dict()")
        else:
            if optional:
                lines.append(f"        if {acc} is not None:")
                lines.append(f"            d['{key}'] = {acc}")
            else:
                lines.append(f"        d['{key}'] = {acc}")
    lines.append("        return d")
    return "\n".join(lines)


def gen_py(schema: dict) -> str:
    props = schema["properties"]
    struct_types = {k: go_name(k) for k, v in props.items() if v["type"] == "object"}
    out = [PY_HEADER, "from __future__ import annotations", "",
           "from dataclasses import dataclass", "from typing import Optional", ""]

    for key, spec in props.items():
        if spec["type"] == "object":
            out.append(_py_dataclass(struct_types[key], spec, {}))
            out.append("")

    out.append(_py_dataclass("Event", schema, struct_types))
    out.append("")

    kinds = props["kind"]["enum"]
    sources = props["source"]["enum"]
    for k in kinds:
        cname = "KIND_" + k.replace(".", "_").upper()
        out.append(f'{cname} = "{k}"')
    out.append("")
    for s in sources:
        out.append(f'SOURCE_{s.upper()} = "{s}"')
    out.append("")
    out.append("KINDS = frozenset({%s})" % ", ".join(f'"{k}"' for k in kinds))
    out.append("SOURCES = frozenset({%s})" % ", ".join(f'"{s}"' for s in sources))
    out.append(f"SCHEMA_VERSION = {schema['x-schema-version']}")
    out.append("")
    return "\n".join(out)


def _gofmt(src: str) -> str:
    """Run gofmt so generated Go is idiomatic and deterministic. gofmt output is
    stable, so `write` and `--check` both apply it and stay consistent. Requires
    gofmt on PATH (it ships with Go); we fail loudly rather than emit unformatted
    code that would then drift the moment anyone runs gofmt."""
    gofmt = shutil.which("gofmt")
    if gofmt is None:
        raise RuntimeError("gofmt not found on PATH; install Go toolchain to run codegen")
    p = subprocess.run([gofmt], input=src, capture_output=True, text=True)
    if p.returncode != 0:
        raise RuntimeError("gofmt failed:\n" + p.stderr)
    return p.stdout.rstrip("\n")


def render() -> dict[str, str]:
    schema = load_schema()
    return {GO_OUT: _gofmt(gen_go(schema)), PY_OUT: gen_py(schema)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if committed files differ from freshly generated")
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--go-only", action="store_true")
    ap.add_argument("--py-only", action="store_true")
    args = ap.parse_args()

    rendered = render()
    if args.stdout:
        if args.go_only:
            sys.stdout.write(rendered[GO_OUT] + "\n")
        elif args.py_only:
            sys.stdout.write(rendered[PY_OUT] + "\n")
        else:
            sys.stdout.write(rendered[GO_OUT] + "\n" + rendered[PY_OUT] + "\n")
        return 0

    if args.check:
        drift = []
        for path, content in rendered.items():
            existing = ""
            if os.path.exists(path):
                with open(path, encoding="utf-8") as f:
                    existing = f.read()
            if existing != content + "\n":
                drift.append(path)
        if drift:
            sys.stderr.write("DRIFT: regenerate with `make gen`:\n  " + "\n  ".join(drift) + "\n")
            return 1
        return 0

    for path, content in rendered.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content + "\n")
        print("wrote", os.path.relpath(path, ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
