# Code generated by shared/schema/gen.py from event.schema.json. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

@dataclass
class Actor:
    pid: int
    ppid: int
    exe: str
    args: list[str]
    user: str

    @classmethod
    def from_dict(cls, d: dict) -> "Actor":
        return cls(
            pid=d['pid'],
            ppid=d['ppid'],
            exe=d['exe'],
            args=d['args'],
            user=d['user'],
        )

    def to_dict(self) -> dict:
        d: dict = {}
        d['pid'] = self.pid
        d['ppid'] = self.ppid
        d['exe'] = self.exe
        d['args'] = self.args
        d['user'] = self.user
        return d

@dataclass
class Target:
    path: Optional[str] = None
    socket: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict) -> "Target":
        return cls(
            path=d.get('path'),
            socket=d.get('socket'),
        )

    def to_dict(self) -> dict:
        d: dict = {}
        if self.path is not None:
            d['path'] = self.path
        if self.socket is not None:
            d['socket'] = self.socket
        return d

@dataclass
class Metrics:
    cpu_pct: Optional[float] = None
    rss_bytes: Optional[int] = None
    temp_c: Optional[float] = None

    @classmethod
    def from_dict(cls, d: dict) -> "Metrics":
        return cls(
            cpu_pct=d.get('cpu_pct'),
            rss_bytes=d.get('rss_bytes'),
            temp_c=d.get('temp_c'),
        )

    def to_dict(self) -> dict:
        d: dict = {}
        if self.cpu_pct is not None:
            d['cpu_pct'] = self.cpu_pct
        if self.rss_bytes is not None:
            d['rss_bytes'] = self.rss_bytes
        if self.temp_c is not None:
            d['temp_c'] = self.temp_c
        return d

@dataclass
class Event:
    id: str
    ts: int
    host_id: str
    kind: str
    actor: Actor
    source: str
    confidence: float
    target: Optional[Target] = None
    metrics: Optional[Metrics] = None

    @classmethod
    def from_dict(cls, d: dict) -> "Event":
        return cls(
            id=d['id'],
            ts=d['ts'],
            host_id=d['host_id'],
            kind=d['kind'],
            actor=Actor.from_dict(d['actor']),
            target=(Target.from_dict(d['target']) if d.get('target') is not None else None),
            metrics=(Metrics.from_dict(d['metrics']) if d.get('metrics') is not None else None),
            source=d['source'],
            confidence=d['confidence'],
        )

    def to_dict(self) -> dict:
        d: dict = {}
        d['id'] = self.id
        d['ts'] = self.ts
        d['host_id'] = self.host_id
        d['kind'] = self.kind
        d['actor'] = self.actor.to_dict()
        if self.target is not None:
            d['target'] = self.target.to_dict()
        if self.metrics is not None:
            d['metrics'] = self.metrics.to_dict()
        d['source'] = self.source
        d['confidence'] = self.confidence
        return d

KIND_HEARTBEAT = "heartbeat"
KIND_PROCESS_SPAWN = "process.spawn"
KIND_PROCESS_EXIT = "process.exit"
KIND_RESOURCE_SAMPLE = "resource.sample"

SOURCE_POLL = "poll"
SOURCE_EBPF = "ebpf"
SOURCE_ES = "es"
SOURCE_ETW = "etw"

KINDS = frozenset({"heartbeat", "process.spawn", "process.exit", "resource.sample"})
SOURCES = frozenset({"poll", "ebpf", "es", "etw"})
SCHEMA_VERSION = 1

